name: Deploy EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Test Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190944421381:role/github-actions-terraform-dev
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

  bootstrap-argocd:
    name: Bootstrap Argo CD
    runs-on: ubuntu-latest

    needs: terraform

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190944421381:role/github-actions-terraform-dev
          aws-region: ap-south-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v5

      - name: Setup Helm
        uses: azure/setup-helm@v5

      - name: Configure EKS kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name test-eks-cluster

      - name: Verify Cluster Access
        run: |
          kubectl get nodes
          kubectl get pods -A

      - name: Add Argo Helm Repository
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

      - name: Install Argo CD
        run: |
          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --version 10.9.2 \
            --wait \
            --timeout 10m

      - name: Configure Argo CD private GitHub repository
        shell: bash
        env:
          GITHUB_APP_ID: ${{ secrets.ARGOCD_GITHUB_APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.ARGOCD_GITHUB_APP_INSTALLATION_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.ARGOCD_GITHUB_APP_PRIVATE_KEY }}

        run: |
          kubectl create secret generic eks-platform-config-repo \
            --namespace argocd \
            --from-literal=type=git \
            --from-literal=url=https://github.com/tusharswami003/eks-platform-config.git \
            --from-literal=githubAppID="$GITHUB_APP_ID" \
            --from-literal=githubAppInstallationID="$GITHUB_APP_INSTALLATION_ID" \
            --from-literal=githubAppPrivateKey="$GITHUB_APP_PRIVATE_KEY" \
            --dry-run=client -o yaml \
          | kubectl label --local -f - \
              argocd.argoproj.io/secret-type=repository \
              -o yaml \
          | kubectl apply -f -

      - name: Bootstrap GitOps Root Application
        run: |
          kubectl apply -f environments/test/argocd/bootstrap/root-app.yaml