name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type DESTROY to confirm destruction of the dev environment'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ inputs.confirm_destroy == 'DESTROY' }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190944421381:role/github-actions-terraform-dev
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve