name: Destroy EKS

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Test Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::190944421381:role/github-actions-terraform-dev
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 
